# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4ad2fae6754d0ed1eda538b3182b7314e7eabc76e5e49da5e688bc68da16c90be285e7d1fc4f4f8ec588ca7b0693ccb71423c7171227481ec33d96b0db2148e

test:
  secret_key_base: 400ccfae20a5fc970591fbc55e7943a8792c8b19c3bd64e59d5ed8f18627ba499369c81e3348058b0ce1bdab3d6cfcb989547f5c959d3a5964089fb940c7553e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
